[package]
name = "otlp-stdout-client"
version = "0.2.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "A custom HTTP client for OpenTelemetry OTLP exporters in serverless environments, writing to stdout for easy integration with AWS Lambda and forwarding to collectors"
repository = "https://github.com/dev7a/lambda-otlp-forwarder/"
readme = "README.md"
keywords = ["opentelemetry", "otlp", "stdout", "lambda", "aws"]
categories = ["development-tools::debugging", "development-tools::profiling", "web-programming"]
homepage = "https://github.com/dev7a/lambda-otlp-forwarder"
documentation = "https://docs.rs/otlp-stdout-client"
exclude = ["tests/*", "examples/*", "benches/*"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
async-trait.workspace = true
http.workspace = true
opentelemetry-http.workspace = true
opentelemetry-otlp.workspace = true
tokio.workspace = true
futures.workspace = true
bytes = "1.7.2"
base64 = "0.22.1"
flate2 = "1.0"

[dev-dependencies]
tokio.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
sealed_test = "1.1.0"   
doc-comment = "0.3"

[[example]]
name = "basic"
path = "examples/basic/main.rs"

