[package]
name = "lambda-lw-http-router"
version = "0.1.3"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "A lightweight, type-safe HTTP router for AWS Lambda functions"
repository = "https://github.com/dev7a/serverless-otlp-forwarder/tree/main/packages/rust/lambda-lw-http-router"
documentation = "https://docs.rs/lambda-lw-http-router"
readme = "README.md"
keywords = ["lambda", "aws", "router", "serverless", "api"]
categories = ["web-programming::http-server", "network-programming"]

[dependencies]
lambda-lw-http-router-core.workspace = true
lambda-lw-http-router-macro.workspace = true
ctor = "0.2"

[dev-dependencies]
lambda_runtime.workspace = true
aws_lambda_events.workspace = true
serde_json.workspace = true
tower = "0.5.1"
tokio.workspace = true
tokio-test = "0.4.4"
doc-comment = "0.3"

[package.metadata.cargo-machete]
ignored = ["ctor"]