[package]
name = "lambda-lw-http-router"
version = "0.1.0"
edition = "2021"
description = "A lightweight, type-safe HTTP router for AWS Lambda functions"
license = "MIT"
repository = "https://github.com/dev7a/lambda-otlp-forwarder/tree/main/packages/rust/lambda-lw-http-router"
documentation = "https://docs.rs/lambda-lw-http-router"
readme = "README.md"
keywords = ["lambda", "aws", "router", "serverless", "api"]
categories = ["web-programming::http-server", "network-programming"]
authors = ["dev7a"]

[dependencies]
lambda-lw-http-router-core = { path = "./router-core", version = "0.1.0" }
lambda-lw-http-router-macro = { path = "./router-macro", version = "0.1.0" }
ctor = "0.2"

[dev-dependencies]
lambda_runtime = "0.13.0"
aws_lambda_events = { version = "0.15.1", features = ["alb", "apigw"] }
serde_json = "1.0"
tower = "0.5.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-test = "0.4.4"
