AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS SAM template for the lambda-otlp-forwarder application.

Parameters:
  RouteAllLogs:
    Type: String
    Default: 'true'
    Description: 'Route all AWS logs to the Lambda function'
  DeployDemo:
    Type: String
    Default: 'true'
    Description: 'Deploy the demo application'
  CollectorsSecretsKeyPrefix:
    Type: String
    Default: 'lambda-otlp-forwarder/keys'
  CollectorsCacheTtlSeconds:
    Type: String
    Default: '300'
  DemoExporterProtocol:
    Type: String
    Default: 'http/protobuf'
  DemoExporterCompression:
    Type: String
    Default: 'gzip'

Conditions:
  RouteAllLogs: !Equals [!Ref RouteAllLogs, 'true']
  DeployDemo: !Equals [!Ref DeployDemo, 'true']
Globals:
  Function:
    MemorySize: 128
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: WARN


Resources:
  LogProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      FunctionName: !Sub '${AWS::StackName}-log-processor'
      CodeUri: ./forwarder/
      Handler: bootstrap
      Runtime: provided.al2023
      Description: !Sub 'Processes logs from AWS Account ${AWS::AccountId}'
      Environment:
        Variables:
          RUST_LOG: info
          OTEL_EXPORTER_OTLP_ENDPOINT: !Sub '{{resolve:secretsmanager:${CollectorsSecretsKeyPrefix}/default:SecretString:endpoint}}'
          OTEL_EXPORTER_OTLP_HEADERS: !Sub '{{resolve:secretsmanager:${CollectorsSecretsKeyPrefix}/default:SecretString:auth}}'
          OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
          COLLECTORS_CACHE_TTL_SECONDS: !Ref CollectorsCacheTtlSeconds
          COLLECTORS_SECRETS_KEY_PREFIX: !Sub '${CollectorsSecretsKeyPrefix}/'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'secretsmanager:BatchGetSecretValue'
                - 'secretsmanager:ListSecrets'
                - 'xray:PutTraceSegments'
                - 'xray:PutSpans'
                - 'xray:PutSpansForIndexing'
              Resource: '*'
            - Effect: Allow
              Action:
                - 'secretsmanager:GetSecretValue'
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CollectorsSecretsKeyPrefix}/*'

  LogProcessorFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LogProcessorFunction
      Action: lambda:InvokeFunction
      Principal: logs.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  LogsAccountPolicy:
    Type: AWS::Logs::AccountPolicy
    Condition: RouteAllLogs
    DependsOn:
      - LogProcessorFunctionPermission
    Properties:
      PolicyName: "LambdaSubscriptionPolicy"
      PolicyDocument: 
        Fn::Sub: |
          {
            "DestinationArn": "${LogProcessorFunction.Arn}",
            "FilterPattern": "{ $.__otel_otlp_stdout = * }",
            "Distribution": "Random"
          }
      PolicyType: "SUBSCRIPTION_FILTER_POLICY"
      Scope: "ALL"
      SelectionCriteria: !Sub "LogGroupName NOT IN [\"/aws/${LogProcessorFunction}\"]"

  DemoStack:
    Type: AWS::Serverless::Application
    Condition: DeployDemo
    Properties:
      Location: ./demo/template.yaml
      Parameters:
        NestedStackName: demo
        ExporterProtocol: !Ref DemoExporterProtocol
        ExporterCompression: !Ref DemoExporterCompression

Outputs:
  LogProcessorFunctionArn:
    Description: 'ARN of the Log Processor Lambda function'
    Value: !GetAtt LogProcessorFunction.Arn
  BackendUrl:
    Condition: DeployDemo
    Description: 'URL of the Backend API'
    Value: !GetAtt DemoStack.Outputs.BackendUrl
  FrontendUrl:
    Condition: DeployDemo
    Description: 'URL of the Frontend Lambda function'
    Value: !GetAtt DemoStack.Outputs.FrontendUrl
