[package]
name = "demo-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros"] }
serde_json = "1.0"
opentelemetry = { version = "0.26.0", features = ["trace"] }
opentelemetry-semantic-conventions = { version = "0.26.0" }
tracing-opentelemetry = "0.27.0"
lambda_runtime = { version = "0.13.0", features = ["anyhow", "tracing", "opentelemetry"] }
tracing = { version = "0.1" }
anyhow = "1.0.88"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12.7", default-features = false, features = ["json", "rustls-tls"] }
opentelemetry-http = "0.26.0"
aws_lambda_events = { version = "0.15.1", default-features = false, features = ["apigw"] }
tower = { version = "0.5.1", features = ["util"] }
aws-config = { version = "1.5.5", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.43.0"
serde_dynamo = { version = "4.2.14", features = ["aws-sdk-dynamodb+1"] }
lazy_static = "1.5.0"
sha2 = "0.10.8"
tera = "1.20.0"
lambda-otel-utils = { path = "../../packages/rust/lambda-otel-utils" }
lambda-lw-http-router = { path = "../../packages/rust/lambda-lw-http-router" }
parking_lot = "0.12"
regex = "1.10"
once_cell = "1.17.2"

[[bin]]
name = "frontend"
path = "src/frontend/main.rs"

[[bin]]
name = "backend"
path = "src/backend/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
