[package]
name = "lambda-lw-http-router-macro"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Procedural macros for lambda-lw-http-router"
repository = "https://github.com/dev7a/lambda-otlp-forwarder/tree/main/packages/rust/lambda-lw-http-router/router-macro"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
darling = "0.20"

[dev-dependencies]
lambda_runtime.workspace = true
aws_lambda_events.workspace = true
serde_json.workspace = true
tower = "0.5.1"
tokio.workspace = true
tokio-test = "0.4.4"
