[package]
name = "lambda-lw-http-router-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
darling = "0.20"
serde_json = "1.0"
lambda_runtime = "0.13.0"
tracing = { version = "0.1", optional = true }
lambda-lw-http-router-core = { path = "../router-core", version = "0.1.0" }


[dev-dependencies]
lambda_runtime = "0.13.0"
aws_lambda_events = { version = "0.15.1", features = ["alb", "apigw"] }
serde_json = "1.0"
tower = "0.5.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-test = "0.4.4"
