[package]
name = "lambda-lw-http-router-core"
version = "0.1.3"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Core functionality for lambda-lw-http-router"
repository = "https://github.com/dev7a/lambda-otlp-forwarder/tree/main/packages/rust/lambda-lw-http-router/router-core"

[dependencies]
serde_json.workspace = true
lambda_runtime.workspace = true
aws_lambda_events.workspace = true
tracing.workspace = true
opentelemetry.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry-http.workspace = true
lazy_static = "1.4.0"
ctor = "0.2.5"
regex = "1.10"

[dev-dependencies]
tokio.workspace = true
http.workspace = true
